"""
ThreatLens Learning Journey - Day 4: Attack Detection
=====================================================

Concept:
In a Security Operations Center (SOC), after logs are parsed (Day 1),
normalized (Day 2), and statistically analyzed (Day 3), the security
pipeline performs Attack Detection.

================================================================================
CRITICAL SOC CONCEPT: ANALYSIS vs. DETECTION
================================================================================

To build effective security monitoring systems, it is essential to understand
the role of each pipeline stage:

  - PARSING (Day 1):
    "What information is inside this raw log?"
    Extracts raw fields from text using regular expressions.

  - NORMALIZATION (Day 2):
    "How do we represent different logs consistently?"
    Maps vendor-specific logs into a canonical schema with common field names.

  - ANALYSIS (Day 3):
    "What is happening in the collected events?"
    Aggregates metrics, counts frequencies, and observes system activity
    without passing judgment (e.g., "10.0.0.50 contacted 7 ports").

  - DETECTION (Day 4):
    "Does the observed behavior match a suspicious pattern?"
    Evaluates normalized events against detection rules and thresholds to
    identify potential security threats (e.g., "7 ports >= threshold 5 -> Alert!").

================================================================================
DETECTION ALERTS ARE SIGNALS, NOT PROOF
================================================================================

An alert generated by a detection rule is NOT automatic proof of a malicious
attack or breach. In real SOC environments, an alert represents a high-fidelity
signal indicating that anomalous or suspicious activity occurred which warrants
investigation by a SOC analyst.

Therefore, detection alerts use cautious, investigative language such as:
  - "Possible port scanning detected"
  - "Possible SSH brute-force activity detected"

Every alert must include actionable EVIDENCE explaining WHY the rule triggered
(e.g., observed count vs. expected threshold) so the analyst can make an informed
decision.

Note: Risk scoring belongs to Day 5. We do NOT calculate risk scores here.
"""

from collections import Counter


# ==============================================================================
# CONFIGURABLE DETECTION THRESHOLDS
# ==============================================================================
# In production SOC / SIEM systems, thresholds are configurable parameters
# tuned according to network baselines to balance sensitivity and false alarms.

PORT_SCAN_THRESHOLD = 5
SSH_BRUTE_FORCE_THRESHOLD = 5


# ==============================================================================
# DETECTION RULES
# ==============================================================================

def detect_port_scan(events, threshold=PORT_SCAN_THRESHOLD):
    """
    Detects potential network port scanning activity.

    Detection Logic:
      1. Filter for network events with valid source IP and destination port.
      2. Group contacted destination ports by source IP.
      3. Count the number of UNIQUE destination ports contacted by each IP.
      4. If unique destination ports >= threshold, generate an alert.

    Real-world Context:
      An adversary conducting reconnaissance scans multiple ports on a target
      to discover running services and potential vulnerabilities. Normal client
      traffic usually connects to only 1-3 distinct services (e.g., 80, 443, 53).

    Args:
        events (list): List of normalized security event dictionaries.
        threshold (int, optional): Minimum unique destination ports required
                                   to trigger an alert. Defaults to PORT_SCAN_THRESHOLD (5).

    Returns:
        list of dict: List of alert dictionaries containing details and evidence.
    """
    # Safe handling: verify input is an iterable list or tuple
    if not events or not isinstance(events, (list, tuple)):
        return []

    # Map each source IP to the set of UNIQUE destination ports it contacted
    ip_ports = {}

    for event in events:
        # Skip malformed or non-dictionary entries safely
        if not isinstance(event, dict):
            continue

        # Port scanning detection inspects network events
        if event.get("event_type") != "network":
            continue

        src_ip = event.get("src_ip")
        dst_port = event.get("dst_port")

        # Skip events missing source IP or destination port
        if not src_ip or dst_port is None:
            continue

        try:
            port_num = int(dst_port)
        except (ValueError, TypeError):
            continue

        if src_ip not in ip_ports:
            ip_ports[src_ip] = set()
        ip_ports[src_ip].add(port_num)

    # Evaluate each source IP against the detection threshold
    alerts = []
    for src_ip in sorted(ip_ports.keys()):
        unique_ports = ip_ports[src_ip]
        unique_count = len(unique_ports)

        if unique_count >= threshold:
            alert = {
                "alert_type": "PORT_SCAN",
                "severity": "HIGH",
                "source_ip": src_ip,
                "description": "Possible port scanning detected",
                "evidence": {
                    "unique_destination_ports": unique_count,
                    "threshold": threshold,
                },
            }
            alerts.append(alert)

    return alerts


def detect_ssh_bruteforce(events, threshold=SSH_BRUTE_FORCE_THRESHOLD):
    """
    Detects potential SSH brute-force authentication attacks.

    Detection Logic:
      1. Filter for authentication events where action indicates login failure.
      2. Group failed attempts by source IP address.
      3. Count the total number of failed attempts per source IP.
      4. If failed attempts >= threshold, generate an alert.

    Real-world Context:
      Attackers use automated tools (e.g., Hydra) to guess passwords across common
      usernames (root, admin, test). Multiple failed authentications from a single
      source IP within a log batch is a strong indicator of brute-force activity.

    Args:
        events (list): List of normalized security event dictionaries.
        threshold (int, optional): Minimum failed login attempts required
                                   to trigger an alert. Defaults to SSH_BRUTE_FORCE_THRESHOLD (5).

    Returns:
        list of dict: List of alert dictionaries containing details and evidence.
    """
    # Safe handling: verify input is an iterable list or tuple
    if not events or not isinstance(events, (list, tuple)):
        return []

    # Count failed logins per source IP
    ip_failures = Counter()

    for event in events:
        # Skip malformed or non-dictionary entries safely
        if not isinstance(event, dict):
            continue

        # Brute-force detection inspects authentication events
        if event.get("event_type") != "authentication":
            continue

        # Look for failed login attempts
        if event.get("action") != "FAILED_LOGIN":
            continue

        src_ip = event.get("src_ip")

        # Skip events without a source IP (e.g. local sudo command events)
        if not src_ip:
            continue

        ip_failures[src_ip] += 1

    # Evaluate each source IP against the detection threshold
    alerts = []
    for src_ip in sorted(ip_failures.keys()):
        failed_count = ip_failures[src_ip]

        if failed_count >= threshold:
            alert = {
                "alert_type": "SSH_BRUTE_FORCE",
                "severity": "HIGH",
                "source_ip": src_ip,
                "description": "Possible SSH brute-force activity detected",
                "evidence": {
                    "failed_attempts": failed_count,
                    "threshold": threshold,
                },
            }
            alerts.append(alert)

    return alerts


# ==============================================================================
# MODULAR DETECTION ENGINE RUNNER
# ==============================================================================

def detect_events(events, port_scan_threshold=PORT_SCAN_THRESHOLD, ssh_threshold=SSH_BRUTE_FORCE_THRESHOLD):
    """
    Modular detection engine that executes all available Day 4 detection rules
    against normalized events and aggregates all generated alerts.

    Args:
        events (list): List of normalized security event dictionaries.
        port_scan_threshold (int, optional): Threshold for port scanning detection.
        ssh_threshold (int, optional): Threshold for SSH brute force detection.

    Returns:
        list of dict: Consolidated list of alerts from all rules.
    """
    if not events or not isinstance(events, (list, tuple)):
        return []

    alerts = []

    # Rule 1: Port Scan Detection
    port_scan_alerts = detect_port_scan(events, threshold=port_scan_threshold)
    alerts.extend(port_scan_alerts)

    # Rule 2: SSH Brute Force Detection
    ssh_alerts = detect_ssh_bruteforce(events, threshold=ssh_threshold)
    alerts.extend(ssh_alerts)

    return alerts


# ==============================================================================
# ALERT REPORT FORMATTING HELPERS
# ==============================================================================

def format_alert(alert):
    """
    Formats a single alert dictionary into human-readable text for SOC display.

    Args:
        alert (dict): An alert dictionary.

    Returns:
        str: Formatted alert block.
    """
    if not isinstance(alert, dict):
        return ""

    lines = [
        "[ALERT]",
        f"Type: {alert.get('alert_type', 'UNKNOWN')}",
        f"Severity: {alert.get('severity', 'UNKNOWN')}",
        f"Source IP: {alert.get('source_ip', 'UNKNOWN')}",
        f"Description: {alert.get('description', '')}",
        "",
        "Evidence:",
    ]

    evidence = alert.get("evidence", {})
    alert_type = alert.get("alert_type")

    if alert_type == "PORT_SCAN":
        lines.append(f"Unique destination ports: {evidence.get('unique_destination_ports')}")
        lines.append(f"Threshold: {evidence.get('threshold')}")
    elif alert_type == "SSH_BRUTE_FORCE":
        lines.append(f"Failed attempts: {evidence.get('failed_attempts')}")
        lines.append(f"Threshold: {evidence.get('threshold')}")
    else:
        for key, val in evidence.items():
            lines.append(f"{key}: {val}")

    return "\n".join(lines)


def format_detection_report(alerts):
    """
    Formats the complete list of alerts into a SOC detection report.

    Args:
        alerts (list): List of alert dictionaries.

    Returns:
        str: Formatted report string.
    """
    lines = [
        "=" * 40,
        "THREATLENS DAY 4 — ATTACK DETECTION",
        "=" * 40,
        "",
        "Running detection rules...",
    ]

    if not alerts:
        lines.append("")
        lines.append("No alerts triggered. All activity is within normal baseline thresholds.")
        return "\n".join(lines)

    for alert in alerts:
        lines.append("")
        lines.append(format_alert(alert))
        lines.append("")
        lines.append("-" * 40)

    return "\n".join(lines)
